# fly.toml app configuration file generated for faris-jewelry-odoo-autumn-dust-7814 on 2025-11-08T19:28:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'faris-jewelry-odoo-autumn-dust-7814'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  ODOO_RC = '/etc/odoo/odoo.conf'

[[mounts]]
  source = 'odoo_data'
  destination = '/var/lib/odoo'

[http_service]
  internal_port = 8069
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/web/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
