app = "faris-jewelry-odoo"

[build]
  dockerfile = "Dockerfile"

[env]
  ODOO_RC = "/etc/odoo/odoo.conf"

[http_service]
  internal_port = 8069
  force_https = true
  
  [[http_service.checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/web"
    timeout = "10s"